In [51]:
import pandas as pd

In [52]:
df1 = pd.read_csv('/home/ubuntu/movie/data/final/85579.csv')
df2 = pd.read_csv('/home/ubuntu/movie/data/after_rating/85579_rating.csv')

In [53]:
for i in range(len(df2['0'])):
    df2['0'][i] = str(df2['0'][i])[0:4]+'-'+str(df2['0'][i])[4:6]+'-'+str(df2['0'][i])[6:8]

/home/ubuntu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [54]:
df2 = df2.rename(columns={'0':'집계날짜'})

In [55]:
df1

,집계날짜,검색량,리뷰,평점,영화코드,영화명,해당일매출액,일일관람객,일일스크린수,일일상영횟수
0,2017-12-20,40.45518,76.020015,84.518861,20150976,신과함께-죄와 벌,2984150800,406365,1538,6818
1,2017-12-21,45.02858,74.014481,82.855994,20150976,신과함께-죄와 벌,2974413400,401449,1582,6955
2,2017-12-22,57.65721,72.526258,81.459370,20150976,신과함께-죄와 벌,4062412398,497810,1653,7458
3,2017-12-23,47.66907,75.437093,82.557422,20150976,신과함께-죄와 벌,8037759271,968372,1818,8426
4,2017-12-24,64.29942,76.230148,82.652955,20150976,신과함께-죄와 벌,10584623400,1268537,1887,8801
5,2017-12-25,58.72074,77.540672,82.772026,20150976,신과함께-죄와 벌,10020464250,1212822,1912,8641
6,2017-12-26,89.25466,70.353424,77.876302,20150976,신과함께-죄와 벌,3195369100,430026,1662,7816
7,2017-12-27,84.97896,74.090715,79.653402,20150976,신과함께-죄와 벌,3021329100,495106,1428,5998
8,2017-12-28,55.95944,72.574956,79.265138,20150976,신과함께-죄와 벌,2803729600,377807,1505,6547
9,2017-12-29,53.18304,71.774194,79.580645,20150976,신과함께-죄와 벌,4414381670,532755,1565,7190
10,2017-12-30,58.40578,71.190320,77.553957,20150976,신과함께-죄와 벌,7556661043,908290,1666,8257
11,2017-12-31,45.72538,69.035674,75.953177,20150976,신과함께-죄와 벌,8568170200,1023957,1663,8332
12,2018-01-01,45.54632,69.230769,75.785256,20150976,신과함께-죄와 벌,7715149100,916652,1644,7957
13,2018-01-02,65.20116,66.572037,74.031228,20150976,신과함께-죄와 벌,2205440800,294339,1446,7019
14,2018-01-03,100.00000,68.964041,76.875000,20150976,신과함께-죄와 벌,1622619700,215987,1241,5724
15,2018-01-04,44.60791,69.931565,76.706587,20150976,신과함께-죄와 벌,1629898600,217032,1226,5525
16,2018-01-05,36.18379,73.030635,78.522976,20150976,신과함께-죄와 벌,2251471243,268181,1211,5497
17,2018-01-06,59.13709,72.100904,78.478916,20150976,신과함께-죄와 벌,4605271262,548337,1260,5536
18,2018-01-07,73.55409,73.996724,78.583129,20150976,신과함께-죄와 벌,4191233200,502236,1258,5464
19,2018-01-08,50.15855,69.543974,77.014115,20150976,신과함께-죄와 벌,1307197900,174358,1171,5192
20,2018-01-09,28.27095,71.549296,77.422535,20150976,신과함께-죄와 벌,1165823200,156343,1182,5155
21,2018-01-10,42.80012,73.867314,82.071197,20150976,신과함께-죄와 벌,1061472000,141824,1170,5039
22,2018-01-11,37.99374,75.657895,81.856725,20150976,신과함께-죄와 벌,926864200,123571,891,3514
23,2018-01-12,57.24517,76.369863,81.205479,20150976,신과함께-죄와 벌,1231166700,146494,920,3623
24,2018-01-13,57.54934,77.097315,82.298658,20150976,신과함께-죄와 벌,2606083100,310297,984,3720
25,2018-01-14,25.25725,77.759336,82.282158,20150976,신과함께-죄와 벌,2416452300,288900,985,3641
26,2018-01-15,22.13569,73.422713,79.889590,20150976,신과함께-죄와 벌,747381200,100000,910,3501
27,2018-01-16,23.97583,75.655431,83.108614,20150976,신과함께-죄와 벌,700064700,95401,948,3493
28,2018-01-17,59.04864,78.756957,83.024119,20150976,신과함께-죄와 벌,530117300,71179,619,2143
29,2018-01-18,35.46542,76.605505,81.123853,20150976,신과함께-죄와 벌,507995300,68978,645,2126
30,2018-01-19,37.15672,74.894515,79.535865,20150976,신과함께-죄와 벌,634859200,76062,645,2129
31,2018-01-20,47.69712,72.207792,80.857143,20150976,신과함께-죄와 벌,1249720800,149485,650,2127

In [56]:
df2

           집계날짜         1          2     3
0    2019-01-12  1.000000  10.000000     1
1    2019-01-09  0.333333   4.666667     3
2    2019-01-07  0.750000   6.000000     2
3    2019-01-06  0.500000   5.000000     4
4    2019-01-05  0.000000   1.000000     1
5    2019-01-04  0.000000   3.500000     2
6    2019-01-03  1.000000   9.000000     1
7    2019-01-02  0.000000   2.000000     2
8    2019-01-01  0.500000   5.000000     7
9    2018-12-31  0.375000   6.000000     4
10   2018-12-30  0.625000   9.500000     4
11   2018-12-26  0.333333   6.000000     3
12   2018-12-25  0.562500   7.625000     8
13   2018-12-24  1.000000  10.000000     1
14   2018-12-21  1.000000  10.000000     1
15   2018-12-20  0.000000   6.000000     1
16   2018-12-19  0.500000   2.000000     1
17   2018-12-17  0.000000   8.000000     1
18   2018-12-15  1.000000  10.000000     1
19   2018-12-11  0.000000   1.500000     2
20   2018-12-10  0.500000  10.000000     1
21   2018-12-09  0.333333   2.333333     3
22   2018-12-06  0.500000   3.500000     2
23   2018-12-05  1.000000  10.000000     1
24   2018-12-02  0.500000   4.500000     2
25   2018-12-01  1.000000  10.000000     1
26   2018-11-30  0.666667   6.000000     3
27   2018-11-29  1.000000   7.000000     3
28   2018-11-27  0.000000   1.000000     1
29   2018-11-26  1.000000  10.000000     1
..          ...       ...        ...   ...
333  2018-01-18  0.729358   8.112385   436
334  2018-01-17  0.752319   8.302412   539
335  2018-01-16  0.735955   8.310861   534
336  2018-01-15  0.712145   7.988959   634
337  2018-01-14  0.736929   8.228216  1205
338  2018-01-13  0.727349   8.229866  1192
339  2018-01-12  0.717123   8.120548   730
340  2018-01-11  0.729532   8.185673   684
341  2018-01-10  0.703074   8.207120   618
342  2018-01-09  0.671831   7.742254   710
343  2018-01-08  0.648751   7.701412   921
344  2018-01-07  0.692875   7.858313  1221
345  2018-01-06  0.685994   7.847892  1328
346  2018-01-05  0.696937   7.852298   914
347  2018-01-04  0.656116   7.670659  1169
348  2018-01-03  0.656678   7.687500  1168
349  2018-01-02  0.626331   7.403123  1409
350  2018-01-01  0.652511   7.578526  1872
351  2017-12-31  0.644091   7.595318  1794
352  2017-12-30  0.670700   7.755396  1529
353  2017-12-29  0.680242   7.958065  1240
354  2017-12-28  0.676661   7.926514  1701
355  2017-12-27  0.698973   7.965340  2337
356  2017-12-26  0.658567   7.787630  3169
357  2017-12-25  0.738749   8.277203  4733
358  2017-12-24  0.725332   8.265295  3841
359  2017-12-23  0.709976   8.255742  2917
360  2017-12-22  0.684356   8.145937  1809
361  2017-12-21  0.686846   8.285599  2486
362  2017-12-20  0.709969   8.451886  2598

[363 rows x 4 columns]

In [57]:
df3 = pd.merge(df1,df2,how='left')

In [58]:
del df3['1']
del df3['2']
df3 = df3.rename(columns={'3':'리뷰수'})

In [59]:
df3

,집계날짜,검색량,리뷰,평점,영화코드,영화명,해당일매출액,일일관람객,일일스크린수,일일상영횟수,리뷰수
0,2017-12-20,40.45518,76.020015,84.518861,20150976,신과함께-죄와 벌,2984150800,406365,1538,6818,2598
1,2017-12-21,45.02858,74.014481,82.855994,20150976,신과함께-죄와 벌,2974413400,401449,1582,6955,2486
2,2017-12-22,57.65721,72.526258,81.459370,20150976,신과함께-죄와 벌,4062412398,497810,1653,7458,1809
3,2017-12-23,47.66907,75.437093,82.557422,20150976,신과함께-죄와 벌,8037759271,968372,1818,8426,2917
4,2017-12-24,64.29942,76.230148,82.652955,20150976,신과함께-죄와 벌,10584623400,1268537,1887,8801,3841
5,2017-12-25,58.72074,77.540672,82.772026,20150976,신과함께-죄와 벌,10020464250,1212822,1912,8641,4733
6,2017-12-26,89.25466,70.353424,77.876302,20150976,신과함께-죄와 벌,3195369100,430026,1662,7816,3169
7,2017-12-27,84.97896,74.090715,79.653402,20150976,신과함께-죄와 벌,3021329100,495106,1428,5998,2337
8,2017-12-28,55.95944,72.574956,79.265138,20150976,신과함께-죄와 벌,2803729600,377807,1505,6547,1701
9,2017-12-29,53.18304,71.774194,79.580645,20150976,신과함께-죄와 벌,4414381670,532755,1565,7190,1240
10,2017-12-30,58.40578,71.190320,77.553957,20150976,신과함께-죄와 벌,7556661043,908290,1666,8257,1529
11,2017-12-31,45.72538,69.035674,75.953177,20150976,신과함께-죄와 벌,8568170200,1023957,1663,8332,1794
12,2018-01-01,45.54632,69.230769,75.785256,20150976,신과함께-죄와 벌,7715149100,916652,1644,7957,1872
13,2018-01-02,65.20116,66.572037,74.031228,20150976,신과함께-죄와 벌,2205440800,294339,1446,7019,1409
14,2018-01-03,100.00000,68.964041,76.875000,20150976,신과함께-죄와 벌,1622619700,215987,1241,5724,1168
15,2018-01-04,44.60791,69.931565,76.706587,20150976,신과함께-죄와 벌,1629898600,217032,1226,5525,1169
16,2018-01-05,36.18379,73.030635,78.522976,20150976,신과함께-죄와 벌,2251471243,268181,1211,5497,914
17,2018-01-06,59.13709,72.100904,78.478916,20150976,신과함께-죄와 벌,4605271262,548337,1260,5536,1328
18,2018-01-07,73.55409,73.996724,78.583129,20150976,신과함께-죄와 벌,4191233200,502236,1258,5464,1221
19,2018-01-08,50.15855,69.543974,77.014115,20150976,신과함께-죄와 벌,1307197900,174358,1171,5192,921
20,2018-01-09,28.27095,71.549296,77.422535,20150976,신과함께-죄와 벌,1165823200,156343,1182,5155,710
21,2018-01-10,42.80012,73.867314,82.071197,20150976,신과함께-죄와 벌,1061472000,141824,1170,5039,618
22,2018-01-11,37.99374,75.657895,81.856725,20150976,신과함께-죄와 벌,926864200,123571,891,3514,684
23,2018-01-12,57.24517,76.369863,81.205479,20150976,신과함께-죄와 벌,1231166700,146494,920,3623,730
24,2018-01-13,57.54934,77.097315,82.298658,20150976,신과함께-죄와 벌,2606083100,310297,984,3720,1192
25,2018-01-14,25.25725,77.759336,82.282158,20150976,신과함께-죄와 벌,2416452300,288900,985,3641,1205
26,2018-01-15,22.13569,73.422713,79.889590,20150976,신과함께-죄와 벌,747381200,100000,910,3501,634
27,2018-01-16,23.97583,75.655431,83.108614,20150976,신과함께-죄와 벌,700064700,95401,948,3493,534
28,2018-01-17,59.04864,78.756957,83.024119,20150976,신과함께-죄와 벌,530117300,71179,619,2143,539
29,2018-01-18,35.46542,76.605505,81.123853,20150976,신과함께-죄와 벌,507995300,68978,645,2126,436
30,2018-01-19,37.15672,74.894515,79.535865,20150976,신과함께-죄와 벌,634859200,76062,645,2129,237
31,2018-01-20,47.69712,72.207792,80.857143,20150976,신과함께-죄와 벌,1249720800,149485,650,2127,385

In [60]:
df3.to_csv('/home/ubuntu/movie/data/85579.csv')